name: XeonGram Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Downgrade Gradle to 8.5
      run: ./gradlew wrapper --gradle-version 8.5

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: XeonGram-APK
        path: app/build/outputs/apk/debug/*.apk
        
